# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: well-permit.oil-gas-commission
  version: '1.0.0'
  description: The well-permit credential issued by Oil and Gas Commission
  path: /oil-gas-commission/well-permit
  attributes:
    - corp_num
    - wa_number
    - well_name
    - well_status
    - issued_date
    - effective_date
    - expiry_date

- name: facility-permit.oil-gas-commission
  version: '1.0.0'
  description: The facility-permit credential issued by Oil and Gas Commission
  path: /oil-gas-commission/facility-permit
  attributes:
    - corp_num
    - facility_id
    - facility_name
    - facility_status
    - issued_date
    - effective_date
    - expiry_date

### eof ###

