issuers:
  myorg:
    credential_types:
    - description: The well-permit credential issued by Oil and Gas Commission
      schema: well-permit.oil-gas-commission
      issuer_url: $ENDPOINT_URL/oil-gas-commission/well-permit
      depends_on:
      - bcreg_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: registration
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
      - model: attribute
        fields:
          type:
            input: wa_number
            from: value
          value:
            input: wa_number
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: well_name
            from: value
          value:
            input: well_name
            from: claim
      - model: attribute
        fields:
          type:
            input: issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: issued_date
            from: claim
      - model: attribute
        fields:
          type:
            input: well_status
            from: value
          value:
            input: well_status
            from: claim
    - description: The facility-permit credential issued by Oil and Gas Commission
      schema: facility-permit.oil-gas-commission
      issuer_url: $ENDPOINT_URL/oil-gas-commission/facility-permit
      depends_on:
      - bcreg_registration
      credential:
        effective_date:
          input: effective_date
          from: claim
        revoked_date:
          input: expiry_date
          from: claim
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: registration
          from: value
      mapping:
      - model: attribute
        fields:
          type:
            input: corp_num
            from: value
          value:
            input: corp_num
            from: claim
      - model: attribute
        fields:
          type:
            input: facility_id
            from: value
          value:
            input: facility_id
            from: claim
      - model: attribute
        fields:
          type:
            input: expiry_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: expiry_date
            from: claim
      - model: attribute
        fields:
          type:
            input: facility_status
            from: value
          value:
            input: facility_status
            from: claim
      - model: attribute
        fields:
          type:
            input: effective_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: effective_date
            from: claim
      - model: attribute
        fields:
          type:
            input: facility_name
            from: value
          value:
            input: facility_name
            from: claim
      - model: attribute
        fields:
          type:
            input: issued_date
            from: value
          format:
            input: datetime
            from: value
          value:
            input: issued_date
            from: claim
