# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: well-permit.oil-gas-commission
  version: '1.0.0'
  description: The well-permit credential issued by Oil and Gas Commission
  endpoint: $ENDPOINT_URL
  path: /oil-gas-commission/well-permit
  # identify the attribute which identify the owning organization
  topic: registration_id
  # optionally identify the credential attribute to map to the TOB credential effective date
  effective_date: effective_date
  # optionally identify the credential attribute to map to the TOB credential revoked date
  revoked_date: expiry_date
  # optionally identify a dependant proof request
  proof_request: bcreg_registration
  attributes:
    registration_id:
      description: ID issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    wa_number:
      description: Well Number
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    well_name:
      description: Well Name
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    well_status:
      description: Well Status
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    issued_date:
      description: Issued Date
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    effective_date:
      description: Effective Date
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    expiry_date:
      description: Expiry Date
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: false

- name: facility-permit.oil-gas-commission
  version: '1.0.0'
  description: The facility-permit credential issued by Oil and Gas Commission
  endpoint: $ENDPOINT_URL
  path: /oil-gas-commission/facility-permit
  # identify the attribute which identify the owning organization
  topic: registration_id
  # optionally identify the credential attribute to map to the TOB credential effective date
  effective_date: effective_date
  # optionally identify the credential attribute to map to the TOB credential revoked date
  revoked_date: expiry_date
  # optionally identify a dependant proof request
  proof_request: bcreg_registration
  attributes:
    registration_id:
      description: ID issued by the registering organization
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    facility_id:
      description: Facility Id
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    facility_name:
      description: Facility Name
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    facility_status:
      description: Facility Status
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    issued_date:
      description: Issued Date
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    effective_date:
      description: Effective Date
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    expiry_date:
      description: Expiry Date
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: false
### eof ###

