# Documentation: https://github.com/bcgov/von-agent-template/tree/master/von-x-agent/config

- name: well-permit.oil-gas-commission
  version: 1.1.4
  description: The well-permit credential issued by Oil and Gas Commission
  topic: registration_id
  cardinality:
    - registration_id
    - wa_number
    - formation_code
  attributes:
    registration_id:
      description: ID issued by the registering organization
      data_type: ui_text
      required: true
    expiry_date:
      description: Expiry Date
      data_type: ui_date
      required: false
    wa_number:
      description: Well Number
      data_type: ui_text
      required: true
    effective_date:
      description: Effective Date
      data_type: ui_date
      required: true
    well_name:
      description: Well Name
      data_type: ui_text
      required: true
    issued_date:
      description: Issued Date
      data_type: ui_date
      required: true
    well_status:
      description: Well Status
      data_type: ui_select
      required: true
    approval_date:
      description: Approval Date
      data_type: ui_date
      required: true
    current_fluid_type:
      description: Current Fluid Type
      data_type: ui_text
      required: true
    formation_description:
      description: Formation Description
      data_type: ui_text
      required: true
    formation_code:
      description: Formation Code
      data_type: ui_text
      required: true
    ground_elevation:
      description: Ground Elevation
      data_type: ui_text
      required: true
    land_type:
      description: Land Type
      data_type: ui_text
      required: true
    geo_latitude:
      description: Geographical Latitude
      data_type: ui_text
      required: true
    geo_longitude:
      description: Geographical Longitude
      data_type: ui_text
      required: true
    well_class:
      description: Well Class
      data_type: ui_text
      required: true
- name: facility-permit.oil-gas-commission
  version: 1.0.0
  description: The facility-permit credential issued by Oil and Gas Commission
  attributes:
    registration_id:
      description: ID issued by the registering organization
      data_type: ui_text
      required: true
    facility_id:
      description: Facility Id
      data_type: ui_text
      required: true
    expiry_date:
      description: Expiry Date
      data_type: ui_date
      required: false
    facility_status:
      description: Facility Status
      data_type: ui_select
      required: true
    effective_date:
      description: Effective Date
      data_type: ui_date
      required: true
    facility_name:
      description: Facility Name
      data_type: ui_text
      required: true
    issued_date:
      description: Issued Date
      data_type: ui_date
      required: true
### eof ###

