version: "3"
services:
  caddyx:
    build:
      context: ../issuer_controller
      dockerfile: Dockerfile.caddy
    environment:
      TOB_API_URL: ${TOB_API_URL}
      WEB_BASE_HREF: ${WEB_BASE_HREF:-/}
      WEB_HOST_NAME: ${WEB_HOST_NAME:-0.0.0.0}
      WEB_HOST_PORT: ${WEB_HOST_PORT:-8080}
      WEB_HOST_TLS: ${WEB_HOST_TLS:-off}
      AGENT_HOST: ${AGENT_HOST:-controller}
      AGENT_PORT: ${AGENT_PORT:-8000}
    networks:
      - oil-gas
    ports:
      - ${WEB_HTTP_PORT:-5000}:${WEB_HOST_PORT:-8080}
    volumes:
      - caddyx-data:/root/.caddy
      - caddyx-logs:/srv/logs

  oil-gas-controller:
    build:
      context: ../issuer_controller
      dockerfile: Dockerfile
    environment:
      CONFIG_ROOT: ../config
      HOST_PORT: ${CONTROLLER_PORT}
      ENVIRONMENT: ${ENVIRONMENT:-default}
      AGENT_ADMIN_URL: http://oil-gas-agent:${AGENT_ADMIN_PORT}
      AGENT_ADMIN_API_KEY: ${AGENT_ADMIN_API_KEY}
      TOB_AGENT_ADMIN_URL: ${TOB_AGENT_ADMIN_URL}
      TOB_ADMIN_API_KEY: ${TOB_ADMIN_API_KEY}
    networks:
      - orgbook
      - oil-gas
    ports:
      - ${EXPOSED_CONTROLLER_PORT}:${CONTROLLER_PORT}
    depends_on:
      - oil-gas-agent
    entrypoint: >
      /bin/bash -c "
        echo sleeping ...;
        sleep 15;
        ../docker-entrypoint.sh;"

  oil-gas-agent:
    image: tob-agent
    environment:
      - LEDGER_URL=${LEDGER_URL}
      - WALLET_TYPE=${WALLET_TYPE}
      - POSTGRESQL_WALLET_HOST=${POSTGRESQL_WALLET_HOST}
      - POSTGRESQL_WALLET_PORT=${POSTGRESQL_WALLET_PORT}
      - POSTGRESQL_WALLET_USER=${POSTGRESQL_USER}
      - POSTGRESQL_WALLET_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_WALLET_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
      - WALLET_ENCRYPTION_KEY=${WALLET_ENCRYPTION_KEY}
      - WALLET_SEED_VONX=${WALLET_SEED_VONX}
      - ISSUER_WALLET_DID=${ISSUER_WALLET_DID}
      - WEBHOOK_URL=${CONTROLLER_URL}/api/agentcb
      - AGENT_HTTP_IN_PORT=${AGENT_HTTP_IN_PORT}
      - AGENT_ADMIN_PORT=${AGENT_ADMIN_PORT}
      - AGENT_NAME=${AGENT_NAME}
    networks:
      - orgbook
      - oil-gas
    ports:
      - ${AGENT_HTTP_IN_PORT}:${AGENT_HTTP_IN_PORT}
      - ${AGENT_ADMIN_PORT}:${AGENT_ADMIN_PORT}
    depends_on:
      - oil-gas-wallet-db
    entrypoint: /bin/bash
    command: [
        "-c",
        "curl -d '{\"seed\":\"${WALLET_SEED_VONX}\", \"role\":\"TRUST_ANCHOR\", \"alias\":\"${AGENT_NAME}\"}' -X POST ${LEDGER_URL}/register; \
        sleep 5; \
        aca-py start \
        --inbound-transport http '0.0.0.0' ${AGENT_HTTP_IN_PORT} \
        --endpoint ${AGENT_ENDPOINT} \
        --outbound-transport http \
        --genesis-url '${LEDGER_URL}/genesis' \
        --auto-ping-connection \
        --auto-respond-messages \
        --auto-respond-credential-offer \
        --auto-respond-presentation-request \
        --auto-verify-presentation \
        --auto-accept-invites \
        --auto-accept-requests \
        --wallet-type 'indy' \
        --wallet-name 'oil_gas_agent_wallet' \
        --wallet-key '${WALLET_ENCRYPTION_KEY}' \
        --wallet-storage-type '${WALLET_TYPE}' \
        --wallet-storage-config '{\"url\":\"${POSTGRESQL_WALLET_HOST}:${POSTGRESQL_WALLET_PORT}\",\"max_connections\":5}' \
        --wallet-storage-creds '{\"account\":\"${POSTGRESQL_USER}\",\"password\":\"${POSTGRESQL_PASSWORD}\",\"admin_account\":\"postgres\",\"admin_password\":\"${POSTGRESQL_ADMIN_PASSWORD}\"}' \
        --seed '${WALLET_SEED_VONX}' \
        --admin '0.0.0.0' ${AGENT_ADMIN_PORT} \
        --${AGENT_ADMIN_MODE} \
        --label ${AGENT_NAME} \
        --plugin indy_catalyst_issuer_registration",
      ]

  oil-gas-wallet-db:
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD}
    networks:
      - orgbook
      - oil-gas
    ports:
      - 5435:5432
    volumes:
      - oil-gas-wallet-db:/var/lib/pgsql/data

volumes:
  caddyx-data:
  caddyx-logs:
  oil-gas-wallet-db:

networks:
  oil-gas:
  orgbook:
    external:
      name: tob_tob
